### ISSUE TITLE
Hardcoded IP adress in source

### ISSUE THREAD

**Issue by magnusjjj** [valentinbreiz/PS4-Linux-Loader#13]
https://github.com/valentinbreiz/PS4-Linux-Loader/blob/0e9d85312d0bc79b544e9dc75fd1cf47fd2a9eb0/source/main.c#L100

That line, right there, tries to contact a statically coded IP adress. If it fails it does not continue but does nothing.
My network was configured so my fathers iphone had that ip adress :P. After debugging for a day or so I found it in the source. I edited the binary with a hex editor to point to my pc and opened a netcat listening port, and sure enough, up popped linux, finally.

**Comment by valentinbreiz** [comment]
It should work after a connection time out normally :/

**Comment by magnusjjj** [comment]
*shrugs* I left it for a couple of minutes. Does it work after a connection is refused? It should, right, unless it triggers some sort of interrupt? Don't.. really know how to test this in a good way. Any suggestions? I would be willing to make a patch if you know a way of doing so without wanting to do something unspeakable xD.
