### ISSUE TITLE
Compilation error.....

### ISSUE THREAD

**Issue by helloitu** [valentinbreiz/PS4-Linux-Loader#6]
some days ago i compiled fine, and all good, but now in the decisive day.. haha

source/main.c:13:13: error: ‘kexec’ redeclared as different kind of symbol
 extern char kexec[];
             ^
In file included from /mnt/d/ps4/ps4-payload-sdk-master//libPS4/include/ps4.h:6:0,
                 from source/main.c:3:
/mnt/d/ps4/ps4-payload-sdk-master//libPS4/include/kernel.h:61:5: note: previous declaration of ‘kexec’ was here
 int kexec(void* func, void* user_arg);

**Comment by valentinbreiz** [comment]
Use this SDK:
https://github.com/valentinbreiz/ps4-payload-sdk

**Comment by helloitu** [comment]
error compiling the sdk

In file included from source/file.c:3:0:
include/file.h:32:2: error: unknown type name ‘__dev_t’
  __dev_t   st_dev;  /* inode's device */
  ^
include/file.h:38:2: error: unknown type name ‘__dev_t’
  __dev_t   st_rdev;  /* device type */
  ^
Makefile:17: recipe for target 'build/file.o' failed
make: *** [build/file.o] Error 1

**Comment by helloitu** [comment]
Solved.
